/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace StealME.Server.Core.Communication.Thrift
{
  /// <summary>
  /// Predefined tracker commands (not really flexible, but it'll do for start)
  /// </summary>
  public enum tracker_command
  {
    ACTIVATE = 0,
    DEACTIVATE = 1,
    UPDATE_STATUS = 2,
    SIGNAL = 3,
  }
}
