//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StealMEModel", "FK_Contact_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StealME.Server.Data.DAL.User), "Contact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StealME.Server.Data.DAL.Contact), true)]
[assembly: EdmRelationshipAttribute("StealMEModel", "FK_Licence_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StealME.Server.Data.DAL.User), "Licence", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StealME.Server.Data.DAL.Licence), true)]
[assembly: EdmRelationshipAttribute("StealMEModel", "FK_CommandQueue_Tracker", "Tracker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StealME.Server.Data.DAL.Tracker), "Command", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StealME.Server.Data.DAL.Command), true)]
[assembly: EdmRelationshipAttribute("StealMEModel", "FK_Licence_Tracker", "Tracker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StealME.Server.Data.DAL.Tracker), "Licence", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StealME.Server.Data.DAL.Licence), true)]
[assembly: EdmRelationshipAttribute("StealMEModel", "FK_Message_Tracker", "Tracker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StealME.Server.Data.DAL.Tracker), "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StealME.Server.Data.DAL.Message), true)]
[assembly: EdmRelationshipAttribute("StealMEModel", "FK_Position_Tracker", "Tracker", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(StealME.Server.Data.DAL.Tracker), "Position", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StealME.Server.Data.DAL.Position), true)]

#endregion

namespace StealME.Server.Data.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StealMEEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StealMEEntities object using the connection string found in the 'StealMEEntities' section of the application configuration file.
        /// </summary>
        public StealMEEntities() : base("name=StealMEEntities", "StealMEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StealMEEntities object.
        /// </summary>
        public StealMEEntities(string connectionString) : base(connectionString, "StealMEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StealMEEntities object.
        /// </summary>
        public StealMEEntities(EntityConnection connection) : base(connection, "StealMEEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Command> Command
        {
            get
            {
                if ((_Command == null))
                {
                    _Command = base.CreateObjectSet<Command>("Command");
                }
                return _Command;
            }
        }
        private ObjectSet<Command> _Command;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contact> Contact
        {
            get
            {
                if ((_Contact == null))
                {
                    _Contact = base.CreateObjectSet<Contact>("Contact");
                }
                return _Contact;
            }
        }
        private ObjectSet<Contact> _Contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Licence> Licence
        {
            get
            {
                if ((_Licence == null))
                {
                    _Licence = base.CreateObjectSet<Licence>("Licence");
                }
                return _Licence;
            }
        }
        private ObjectSet<Licence> _Licence;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Message
        {
            get
            {
                if ((_Message == null))
                {
                    _Message = base.CreateObjectSet<Message>("Message");
                }
                return _Message;
            }
        }
        private ObjectSet<Message> _Message;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Position> Position
        {
            get
            {
                if ((_Position == null))
                {
                    _Position = base.CreateObjectSet<Position>("Position");
                }
                return _Position;
            }
        }
        private ObjectSet<Position> _Position;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tracker> Tracker
        {
            get
            {
                if ((_Tracker == null))
                {
                    _Tracker = base.CreateObjectSet<Tracker>("Tracker");
                }
                return _Tracker;
            }
        }
        private ObjectSet<Tracker> _Tracker;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Command EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommand(Command command)
        {
            base.AddObject("Command", command);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContact(Contact contact)
        {
            base.AddObject("Contact", contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Licence EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLicence(Licence licence)
        {
            base.AddObject("Licence", licence);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage(Message message)
        {
            base.AddObject("Message", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Position EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosition(Position position)
        {
            base.AddObject("Position", position);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tracker EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTracker(Tracker tracker)
        {
            base.AddObject("Tracker", tracker);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="Command")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Command : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Command object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="trackerId">Initial value of the TrackerId property.</param>
        /// <param name="commandText">Initial value of the CommandText property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        public static Command CreateCommand(global::System.Guid id, global::System.Guid trackerId, global::System.String commandText, global::System.DateTime creationDate)
        {
            Command command = new Command();
            command.Id = id;
            command.TrackerId = trackerId;
            command.CommandText = commandText;
            command.CreationDate = creationDate;
            return command;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TrackerId
        {
            get
            {
                return _TrackerId;
            }
            set
            {
                OnTrackerIdChanging(value);
                ReportPropertyChanging("TrackerId");
                _TrackerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackerId");
                OnTrackerIdChanged();
            }
        }
        private global::System.Guid _TrackerId;
        partial void OnTrackerIdChanging(global::System.Guid value);
        partial void OnTrackerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommandText
        {
            get
            {
                return _CommandText;
            }
            set
            {
                OnCommandTextChanging(value);
                ReportPropertyChanging("CommandText");
                _CommandText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommandText");
                OnCommandTextChanged();
            }
        }
        private global::System.String _CommandText;
        partial void OnCommandTextChanging(global::System.String value);
        partial void OnCommandTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_CommandQueue_Tracker", "Tracker")]
        public Tracker Tracker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_CommandQueue_Tracker", "Tracker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_CommandQueue_Tracker", "Tracker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tracker> TrackerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_CommandQueue_Tracker", "Tracker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tracker>("StealMEModel.FK_CommandQueue_Tracker", "Tracker", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="address2">Initial value of the Address2 property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Contact CreateContact(global::System.Guid id, global::System.Guid userId, global::System.String firstName, global::System.String lastName, global::System.String zip, global::System.String country, global::System.String address, global::System.String address2, global::System.String phone, global::System.String email)
        {
            Contact contact = new Contact();
            contact.Id = id;
            contact.UserId = userId;
            contact.FirstName = firstName;
            contact.LastName = lastName;
            contact.Zip = zip;
            contact.Country = country;
            contact.Address = address;
            contact.Address2 = address2;
            contact.Phone = phone;
            contact.Email = email;
            return contact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Contact_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StealMEModel.FK_Contact_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StealMEModel.FK_Contact_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StealMEModel.FK_Contact_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("StealMEModel.FK_Contact_User", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="Licence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Licence : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Licence object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="trackerId">Initial value of the TrackerId property.</param>
        /// <param name="validFrom">Initial value of the ValidFrom property.</param>
        /// <param name="validUntil">Initial value of the ValidUntil property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static Licence CreateLicence(global::System.Guid id, global::System.Guid trackerId, global::System.DateTime validFrom, global::System.DateTime validUntil, global::System.DateTime creationDate, global::System.Guid userId)
        {
            Licence licence = new Licence();
            licence.Id = id;
            licence.TrackerId = trackerId;
            licence.ValidFrom = validFrom;
            licence.ValidUntil = validUntil;
            licence.CreationDate = creationDate;
            licence.UserId = userId;
            return licence;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TrackerId
        {
            get
            {
                return _TrackerId;
            }
            set
            {
                OnTrackerIdChanging(value);
                ReportPropertyChanging("TrackerId");
                _TrackerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackerId");
                OnTrackerIdChanged();
            }
        }
        private global::System.Guid _TrackerId;
        partial void OnTrackerIdChanging(global::System.Guid value);
        partial void OnTrackerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ValidFrom
        {
            get
            {
                return _ValidFrom;
            }
            set
            {
                OnValidFromChanging(value);
                ReportPropertyChanging("ValidFrom");
                _ValidFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidFrom");
                OnValidFromChanged();
            }
        }
        private global::System.DateTime _ValidFrom;
        partial void OnValidFromChanging(global::System.DateTime value);
        partial void OnValidFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ValidUntil
        {
            get
            {
                return _ValidUntil;
            }
            set
            {
                OnValidUntilChanging(value);
                ReportPropertyChanging("ValidUntil");
                _ValidUntil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidUntil");
                OnValidUntilChanged();
            }
        }
        private global::System.DateTime _ValidUntil;
        partial void OnValidUntilChanging(global::System.DateTime value);
        partial void OnValidUntilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Licence_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StealMEModel.FK_Licence_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StealMEModel.FK_Licence_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("StealMEModel.FK_Licence_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("StealMEModel.FK_Licence_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Licence_Tracker", "Tracker")]
        public Tracker Tracker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Licence_Tracker", "Tracker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Licence_Tracker", "Tracker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tracker> TrackerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Licence_Tracker", "Tracker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tracker>("StealMEModel.FK_Licence_Tracker", "Tracker", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="trackerId">Initial value of the TrackerId property.</param>
        public static Message CreateMessage(global::System.Guid id, global::System.DateTime creationDate, global::System.Guid trackerId)
        {
            Message message = new Message();
            message.Id = id;
            message.CreationDate = creationDate;
            message.TrackerId = trackerId;
            return message;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message1
        {
            get
            {
                return _Message1;
            }
            set
            {
                OnMessage1Changing(value);
                ReportPropertyChanging("Message1");
                _Message1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message1");
                OnMessage1Changed();
            }
        }
        private global::System.String _Message1;
        partial void OnMessage1Changing(global::System.String value);
        partial void OnMessage1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TrackerId
        {
            get
            {
                return _TrackerId;
            }
            set
            {
                OnTrackerIdChanging(value);
                ReportPropertyChanging("TrackerId");
                _TrackerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackerId");
                OnTrackerIdChanged();
            }
        }
        private global::System.Guid _TrackerId;
        partial void OnTrackerIdChanging(global::System.Guid value);
        partial void OnTrackerIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Message_Tracker", "Tracker")]
        public Tracker Tracker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Message_Tracker", "Tracker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Message_Tracker", "Tracker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tracker> TrackerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Message_Tracker", "Tracker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tracker>("StealMEModel.FK_Message_Tracker", "Tracker", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="Position")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Position : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Position object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="trackerId">Initial value of the TrackerId property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        /// <param name="longtitude">Initial value of the Longtitude property.</param>
        public static Position CreatePosition(global::System.Guid id, global::System.Guid trackerId, global::System.DateTime creationDate, global::System.String latitude, global::System.String longtitude)
        {
            Position position = new Position();
            position.Id = id;
            position.TrackerId = trackerId;
            position.CreationDate = creationDate;
            position.Latitude = latitude;
            position.Longtitude = longtitude;
            return position;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TrackerId
        {
            get
            {
                return _TrackerId;
            }
            set
            {
                OnTrackerIdChanging(value);
                ReportPropertyChanging("TrackerId");
                _TrackerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrackerId");
                OnTrackerIdChanged();
            }
        }
        private global::System.Guid _TrackerId;
        partial void OnTrackerIdChanging(global::System.Guid value);
        partial void OnTrackerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Longtitude
        {
            get
            {
                return _Longtitude;
            }
            set
            {
                OnLongtitudeChanging(value);
                ReportPropertyChanging("Longtitude");
                _Longtitude = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Longtitude");
                OnLongtitudeChanged();
            }
        }
        private global::System.String _Longtitude;
        partial void OnLongtitudeChanging(global::System.String value);
        partial void OnLongtitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellId
        {
            get
            {
                return _CellId;
            }
            set
            {
                OnCellIdChanging(value);
                ReportPropertyChanging("CellId");
                _CellId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CellId");
                OnCellIdChanged();
            }
        }
        private global::System.String _CellId;
        partial void OnCellIdChanging(global::System.String value);
        partial void OnCellIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rssi
        {
            get
            {
                return _Rssi;
            }
            set
            {
                OnRssiChanging(value);
                ReportPropertyChanging("Rssi");
                _Rssi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rssi");
                OnRssiChanged();
            }
        }
        private global::System.String _Rssi;
        partial void OnRssiChanging(global::System.String value);
        partial void OnRssiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mnc
        {
            get
            {
                return _Mnc;
            }
            set
            {
                OnMncChanging(value);
                ReportPropertyChanging("Mnc");
                _Mnc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mnc");
                OnMncChanged();
            }
        }
        private global::System.String _Mnc;
        partial void OnMncChanging(global::System.String value);
        partial void OnMncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mcc
        {
            get
            {
                return _Mcc;
            }
            set
            {
                OnMccChanging(value);
                ReportPropertyChanging("Mcc");
                _Mcc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mcc");
                OnMccChanged();
            }
        }
        private global::System.String _Mcc;
        partial void OnMccChanging(global::System.String value);
        partial void OnMccChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Acc
        {
            get
            {
                return _Acc;
            }
            set
            {
                OnAccChanging(value);
                ReportPropertyChanging("Acc");
                _Acc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Acc");
                OnAccChanged();
            }
        }
        private global::System.String _Acc;
        partial void OnAccChanging(global::System.String value);
        partial void OnAccChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Position_Tracker", "Tracker")]
        public Tracker Tracker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Position_Tracker", "Tracker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Position_Tracker", "Tracker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tracker> TrackerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tracker>("StealMEModel.FK_Position_Tracker", "Tracker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tracker>("StealMEModel.FK_Position_Tracker", "Tracker", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="Tracker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tracker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tracker object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="iMEI">Initial value of the IMEI property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Tracker CreateTracker(global::System.Guid id, global::System.String iMEI, global::System.DateTime creationDate, global::System.String name, global::System.String description)
        {
            Tracker tracker = new Tracker();
            tracker.Id = id;
            tracker.IMEI = iMEI;
            tracker.CreationDate = creationDate;
            tracker.Name = name;
            tracker.Description = description;
            return tracker;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private global::System.String _IMEI;
        partial void OnIMEIChanging(global::System.String value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastKnownState
        {
            get
            {
                return _LastKnownState;
            }
            set
            {
                OnLastKnownStateChanging(value);
                ReportPropertyChanging("LastKnownState");
                _LastKnownState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastKnownState");
                OnLastKnownStateChanged();
            }
        }
        private global::System.String _LastKnownState;
        partial void OnLastKnownStateChanging(global::System.String value);
        partial void OnLastKnownStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsOnline
        {
            get
            {
                return _IsOnline;
            }
            set
            {
                OnIsOnlineChanging(value);
                ReportPropertyChanging("IsOnline");
                _IsOnline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsOnline");
                OnIsOnlineChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsOnline;
        partial void OnIsOnlineChanging(Nullable<global::System.Boolean> value);
        partial void OnIsOnlineChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_CommandQueue_Tracker", "Command")]
        public EntityCollection<Command> Command
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Command>("StealMEModel.FK_CommandQueue_Tracker", "Command");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Command>("StealMEModel.FK_CommandQueue_Tracker", "Command", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Licence_Tracker", "Licence")]
        public EntityCollection<Licence> Licence
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Licence>("StealMEModel.FK_Licence_Tracker", "Licence");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Licence>("StealMEModel.FK_Licence_Tracker", "Licence", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Message_Tracker", "Message")]
        public EntityCollection<Message> Message
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message>("StealMEModel.FK_Message_Tracker", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message>("StealMEModel.FK_Message_Tracker", "Message", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Position_Tracker", "Position")]
        public EntityCollection<Position> Position
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Position>("StealMEModel.FK_Position_Tracker", "Position");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Position>("StealMEModel.FK_Position_Tracker", "Position", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StealMEModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="isActivated">Initial value of the IsActivated property.</param>
        /// <param name="isLockedOut">Initial value of the IsLockedOut property.</param>
        public static User CreateUser(global::System.Guid id, global::System.String name, global::System.DateTime creationDate, global::System.String password, global::System.Boolean isActivated, global::System.Boolean isLockedOut)
        {
            User user = new User();
            user.Id = id;
            user.Name = name;
            user.CreationDate = creationDate;
            user.Password = password;
            user.IsActivated = isActivated;
            user.IsLockedOut = isLockedOut;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordSalt
        {
            get
            {
                return _PasswordSalt;
            }
            set
            {
                OnPasswordSaltChanging(value);
                ReportPropertyChanging("PasswordSalt");
                _PasswordSalt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordSalt");
                OnPasswordSaltChanged();
            }
        }
        private global::System.String _PasswordSalt;
        partial void OnPasswordSaltChanging(global::System.String value);
        partial void OnPasswordSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastModifiedDate;
        partial void OnLastModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastLoginIp
        {
            get
            {
                return _LastLoginIp;
            }
            set
            {
                OnLastLoginIpChanging(value);
                ReportPropertyChanging("LastLoginIp");
                _LastLoginIp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastLoginIp");
                OnLastLoginIpChanged();
            }
        }
        private global::System.String _LastLoginIp;
        partial void OnLastLoginIpChanging(global::System.String value);
        partial void OnLastLoginIpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActivated
        {
            get
            {
                return _IsActivated;
            }
            set
            {
                OnIsActivatedChanging(value);
                ReportPropertyChanging("IsActivated");
                _IsActivated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActivated");
                OnIsActivatedChanged();
            }
        }
        private global::System.Boolean _IsActivated;
        partial void OnIsActivatedChanging(global::System.Boolean value);
        partial void OnIsActivatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsLockedOut
        {
            get
            {
                return _IsLockedOut;
            }
            set
            {
                OnIsLockedOutChanging(value);
                ReportPropertyChanging("IsLockedOut");
                _IsLockedOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLockedOut");
                OnIsLockedOutChanged();
            }
        }
        private global::System.Boolean _IsLockedOut;
        partial void OnIsLockedOutChanging(global::System.Boolean value);
        partial void OnIsLockedOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewPasswordKey
        {
            get
            {
                return _NewPasswordKey;
            }
            set
            {
                OnNewPasswordKeyChanging(value);
                ReportPropertyChanging("NewPasswordKey");
                _NewPasswordKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewPasswordKey");
                OnNewPasswordKeyChanged();
            }
        }
        private global::System.String _NewPasswordKey;
        partial void OnNewPasswordKeyChanging(global::System.String value);
        partial void OnNewPasswordKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NewPasswordRequested
        {
            get
            {
                return _NewPasswordRequested;
            }
            set
            {
                OnNewPasswordRequestedChanging(value);
                ReportPropertyChanging("NewPasswordRequested");
                _NewPasswordRequested = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewPasswordRequested");
                OnNewPasswordRequestedChanged();
            }
        }
        private Nullable<global::System.DateTime> _NewPasswordRequested;
        partial void OnNewPasswordRequestedChanging(Nullable<global::System.DateTime> value);
        partial void OnNewPasswordRequestedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewEmail
        {
            get
            {
                return _NewEmail;
            }
            set
            {
                OnNewEmailChanging(value);
                ReportPropertyChanging("NewEmail");
                _NewEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewEmail");
                OnNewEmailChanged();
            }
        }
        private global::System.String _NewEmail;
        partial void OnNewEmailChanging(global::System.String value);
        partial void OnNewEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewEmailKey
        {
            get
            {
                return _NewEmailKey;
            }
            set
            {
                OnNewEmailKeyChanging(value);
                ReportPropertyChanging("NewEmailKey");
                _NewEmailKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewEmailKey");
                OnNewEmailKeyChanged();
            }
        }
        private global::System.String _NewEmailKey;
        partial void OnNewEmailKeyChanging(global::System.String value);
        partial void OnNewEmailKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NewEmailRequested
        {
            get
            {
                return _NewEmailRequested;
            }
            set
            {
                OnNewEmailRequestedChanging(value);
                ReportPropertyChanging("NewEmailRequested");
                _NewEmailRequested = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewEmailRequested");
                OnNewEmailRequestedChanged();
            }
        }
        private Nullable<global::System.DateTime> _NewEmailRequested;
        partial void OnNewEmailRequestedChanging(Nullable<global::System.DateTime> value);
        partial void OnNewEmailRequestedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastLockedOutReason
        {
            get
            {
                return _LastLockedOutReason;
            }
            set
            {
                OnLastLockedOutReasonChanging(value);
                ReportPropertyChanging("LastLockedOutReason");
                _LastLockedOutReason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastLockedOutReason");
                OnLastLockedOutReasonChanged();
            }
        }
        private global::System.String _LastLockedOutReason;
        partial void OnLastLockedOutReasonChanging(global::System.String value);
        partial void OnLastLockedOutReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLockedOutDate
        {
            get
            {
                return _LastLockedOutDate;
            }
            set
            {
                OnLastLockedOutDateChanging(value);
                ReportPropertyChanging("LastLockedOutDate");
                _LastLockedOutDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLockedOutDate");
                OnLastLockedOutDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLockedOutDate;
        partial void OnLastLockedOutDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLockedOutDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Contact_User", "Contact")]
        public EntityCollection<Contact> Contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Contact>("StealMEModel.FK_Contact_User", "Contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Contact>("StealMEModel.FK_Contact_User", "Contact", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StealMEModel", "FK_Licence_User", "Licence")]
        public EntityCollection<Licence> Licence
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Licence>("StealMEModel.FK_Licence_User", "Licence");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Licence>("StealMEModel.FK_Licence_User", "Licence", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
